ALTER TABLE tickets ADD COLUMN IF NOT EXISTS author_email TEXT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS assigned_to_email TEXT;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS department TEXT;
